elastica_random_control:
  ros__parameters:
    queue_size: 10
    print_params: 1
    pub_frequency: 2.0
    topic_names: ['/elastica/control_input','/elastica/time_tracker','/elastica/rod_state']
    