#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'elastica-sim-control==0.1.1','console_scripts','continuum_snake_ros2'
__requires__ = 'elastica-sim-control==0.1.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('elastica-sim-control==0.1.1', 'console_scripts', 'continuum_snake_ros2')()
    )
